generate_content:
  name: Generate content
  description: Generate content using Yanfeng AI Task.
  fields:
    prompt:
      name: Prompt
      description: The prompt to generate content from.
      required: true
      selector:
        text:
          multiline: true
    model:
      name: Model
      description: The model to use for generation.
      required: false
      default: "qwen-plus"
      selector:
        select:
          options:
            - "qwen-turbo"
            - "qwen-plus"
            - "qwen-max"
            - "qwen-vl-plus"
            - "qwen-vl-max"
    temperature:
      name: Temperature
      description: Controls randomness in the output.
      required: false
      default: 0.7
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
    max_tokens:
      name: Max Tokens
      description: Maximum number of tokens to generate.
      required: false
      default: 2048
      selector:
        number:
          min: 1
          max: 8192
          step: 1